classDiagram
    class ProgressBar {
        -value
    }

    class Thread

    class ProgressBarManager {
        +ProgressBarManager(progressBar: ProgressBar, asyncProgressBar: AsyncProgressBar)
        +run()
    }

    class AsyncProgressBar
    class HW

    %% ereditarietà (il manager è un thread)
    ProgressBarManager --|> Thread

    %% relazione a sinistra: il manager contiene/gestisce 1 ProgressBar
    ProgressBarManager o-- "1" ProgressBar

    %% relazione a destra: un contenitore (HW) possiede il manager
    HW o-- "1" ProgressBarManager
